### ISSUE TITLE
Add section for mouse configuration

### ISSUE THREAD

**Issue by luzpaz** [howie-j/FreeCAD-Wizard#4]
Section can allow the user to set their preferred mouse preferences

* https://wiki.freecad.org/Mouse_navigation
* https://wiki.freecad.org/3Dconnexion_input_devices

![Screenshot_20220821_151220](https://user-images.githubusercontent.com/4140247/185807155-8c9c4682-68c8-4ab8-8299-d34e7701f532.png)

**Comment by howie-j** [comment]
Absolutely! Preferably with a GIF or text information to help select the one they are used to.

**Comment by howie-j** [comment]
Added.
