### ISSUE TITLE
Add section to choose language locale and preferred units

### ISSUE THREAD

**Issue by luzpaz** [howie-j/FreeCAD-Wizard#5]
![Screenshot_20220821_151839](https://user-images.githubusercontent.com/4140247/185807349-777ed40b-57b4-4c2e-8400-c408195cbb8a.png)

![Screenshot_20220821_151921](https://user-images.githubusercontent.com/4140247/185807361-da844b29-ffd4-4c97-823c-9be80607d51b.png)

**Comment by howie-j** [comment]
Aah of course, perhaps the most important.

**Comment by howie-j** [comment]
Added.
